// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glugubilvxufzkqedtou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsdWd1Ymlsdnh1ZnprcWVkdG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NzE5MDYsImV4cCI6MjA1MjE0NzkwNn0.UUyqaVfjTmgVWHjhi6HbcqkSV8pvbOuD0TCLg_Butsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);